#!/usr/bin/env node

const http = require('http')
const httpProxy = require('http-proxy')
const proxy = httpProxy.createProxyServer()
const isAcmeChallengePath = require('./lib/is-acme-challenge-path')

http.createServer((req, res) => {
  console.log(req.url)
  if (isAcmeChallengePath(req.url)) {
    proxy.web(req, res, {target: 'http://127.0.0.1:13135'})
  } else {
    res.statusCode = 404
    res.end()
  }
}).listen(5002)
